################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../autogen/sl_board_default_init.c \
../autogen/sl_device_init_clocks.c \
../autogen/sl_event_handler.c \
../autogen/sl_usbd_class_cdc_acm_instances.c \
../autogen/sl_usbd_class_vendor_instances.c \
../autogen/sl_usbd_configuration_instances.c \
../autogen/sl_usbd_init.c 

OBJS += \
./autogen/sl_board_default_init.o \
./autogen/sl_device_init_clocks.o \
./autogen/sl_event_handler.o \
./autogen/sl_usbd_class_cdc_acm_instances.o \
./autogen/sl_usbd_class_vendor_instances.o \
./autogen/sl_usbd_configuration_instances.o \
./autogen/sl_usbd_init.o 

C_DEPS += \
./autogen/sl_board_default_init.d \
./autogen/sl_device_init_clocks.d \
./autogen/sl_event_handler.d \
./autogen/sl_usbd_class_cdc_acm_instances.d \
./autogen/sl_usbd_class_vendor_instances.d \
./autogen/sl_usbd_configuration_instances.d \
./autogen/sl_usbd_init.d 


# Each subdirectory must supply rules for building sources it contributes
autogen/sl_board_default_init.o: ../autogen/sl_board_default_init.c autogen/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DUSBD_CFG_MS_OS_DESC_EN=1' '-DGECKO_DEVICE_CLASS_VENDOR_DESCRIPTION_PROPERTY_LEN=64' '-DEFM32GG11B820F2048GL192=1' '-DHFXO_FREQ=50000000' '-DSL_BOARD_NAME="BRD2204C"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DSL_USBD_VENDOR_MS_EXTENDED_PROPERTIES_QUANTITY=1' -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\config" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\autogen" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\Device\SiliconLabs\EFM32GG11B\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\common\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\hardware\board\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\CMSIS\Core\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\CMSIS\RTOS2\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\device_init\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\emlib\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\cmsis\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\kernel\include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\kernel\portable\GCC\ARM_CM4F" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\silicon_labs\silabs_core\memory_manager" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\common\toolchain\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\system\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\udelay\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\protocol\usb\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\protocol\usb\src" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"autogen/sl_board_default_init.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

autogen/sl_device_init_clocks.o: ../autogen/sl_device_init_clocks.c autogen/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DUSBD_CFG_MS_OS_DESC_EN=1' '-DGECKO_DEVICE_CLASS_VENDOR_DESCRIPTION_PROPERTY_LEN=64' '-DEFM32GG11B820F2048GL192=1' '-DHFXO_FREQ=50000000' '-DSL_BOARD_NAME="BRD2204C"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DSL_USBD_VENDOR_MS_EXTENDED_PROPERTIES_QUANTITY=1' -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\config" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\autogen" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\Device\SiliconLabs\EFM32GG11B\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\common\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\hardware\board\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\CMSIS\Core\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\CMSIS\RTOS2\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\device_init\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\emlib\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\cmsis\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\kernel\include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\kernel\portable\GCC\ARM_CM4F" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\silicon_labs\silabs_core\memory_manager" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\common\toolchain\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\system\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\udelay\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\protocol\usb\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\protocol\usb\src" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"autogen/sl_device_init_clocks.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

autogen/sl_event_handler.o: ../autogen/sl_event_handler.c autogen/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DUSBD_CFG_MS_OS_DESC_EN=1' '-DGECKO_DEVICE_CLASS_VENDOR_DESCRIPTION_PROPERTY_LEN=64' '-DEFM32GG11B820F2048GL192=1' '-DHFXO_FREQ=50000000' '-DSL_BOARD_NAME="BRD2204C"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DSL_USBD_VENDOR_MS_EXTENDED_PROPERTIES_QUANTITY=1' -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\config" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\autogen" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\Device\SiliconLabs\EFM32GG11B\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\common\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\hardware\board\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\CMSIS\Core\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\CMSIS\RTOS2\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\device_init\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\emlib\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\cmsis\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\kernel\include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\kernel\portable\GCC\ARM_CM4F" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\silicon_labs\silabs_core\memory_manager" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\common\toolchain\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\system\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\udelay\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\protocol\usb\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\protocol\usb\src" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"autogen/sl_event_handler.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

autogen/sl_usbd_class_cdc_acm_instances.o: ../autogen/sl_usbd_class_cdc_acm_instances.c autogen/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DUSBD_CFG_MS_OS_DESC_EN=1' '-DGECKO_DEVICE_CLASS_VENDOR_DESCRIPTION_PROPERTY_LEN=64' '-DEFM32GG11B820F2048GL192=1' '-DHFXO_FREQ=50000000' '-DSL_BOARD_NAME="BRD2204C"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DSL_USBD_VENDOR_MS_EXTENDED_PROPERTIES_QUANTITY=1' -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\config" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\autogen" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\Device\SiliconLabs\EFM32GG11B\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\common\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\hardware\board\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\CMSIS\Core\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\CMSIS\RTOS2\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\device_init\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\emlib\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\cmsis\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\kernel\include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\kernel\portable\GCC\ARM_CM4F" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\silicon_labs\silabs_core\memory_manager" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\common\toolchain\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\system\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\udelay\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\protocol\usb\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\protocol\usb\src" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"autogen/sl_usbd_class_cdc_acm_instances.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

autogen/sl_usbd_class_vendor_instances.o: ../autogen/sl_usbd_class_vendor_instances.c autogen/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DUSBD_CFG_MS_OS_DESC_EN=1' '-DGECKO_DEVICE_CLASS_VENDOR_DESCRIPTION_PROPERTY_LEN=64' '-DEFM32GG11B820F2048GL192=1' '-DHFXO_FREQ=50000000' '-DSL_BOARD_NAME="BRD2204C"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DSL_USBD_VENDOR_MS_EXTENDED_PROPERTIES_QUANTITY=1' -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\config" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\autogen" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\Device\SiliconLabs\EFM32GG11B\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\common\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\hardware\board\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\CMSIS\Core\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\CMSIS\RTOS2\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\device_init\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\emlib\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\cmsis\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\kernel\include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\kernel\portable\GCC\ARM_CM4F" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\silicon_labs\silabs_core\memory_manager" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\common\toolchain\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\system\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\udelay\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\protocol\usb\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\protocol\usb\src" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"autogen/sl_usbd_class_vendor_instances.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

autogen/sl_usbd_configuration_instances.o: ../autogen/sl_usbd_configuration_instances.c autogen/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DUSBD_CFG_MS_OS_DESC_EN=1' '-DGECKO_DEVICE_CLASS_VENDOR_DESCRIPTION_PROPERTY_LEN=64' '-DEFM32GG11B820F2048GL192=1' '-DHFXO_FREQ=50000000' '-DSL_BOARD_NAME="BRD2204C"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DSL_USBD_VENDOR_MS_EXTENDED_PROPERTIES_QUANTITY=1' -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\config" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\autogen" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\Device\SiliconLabs\EFM32GG11B\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\common\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\hardware\board\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\CMSIS\Core\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\CMSIS\RTOS2\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\device_init\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\emlib\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\cmsis\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\kernel\include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\kernel\portable\GCC\ARM_CM4F" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\silicon_labs\silabs_core\memory_manager" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\common\toolchain\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\system\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\udelay\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\protocol\usb\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\protocol\usb\src" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"autogen/sl_usbd_configuration_instances.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

autogen/sl_usbd_init.o: ../autogen/sl_usbd_init.c autogen/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DUSBD_CFG_MS_OS_DESC_EN=1' '-DGECKO_DEVICE_CLASS_VENDOR_DESCRIPTION_PROPERTY_LEN=64' '-DEFM32GG11B820F2048GL192=1' '-DHFXO_FREQ=50000000' '-DSL_BOARD_NAME="BRD2204C"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DSL_USBD_VENDOR_MS_EXTENDED_PROPERTIES_QUANTITY=1' -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\config" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\autogen" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\Device\SiliconLabs\EFM32GG11B\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\common\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\hardware\board\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\CMSIS\Core\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\CMSIS\RTOS2\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\device_init\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\emlib\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\cmsis\Include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\kernel\include" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\third_party\freertos\kernel\portable\GCC\ARM_CM4F" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\util\silicon_labs\silabs_core\memory_manager" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\common\toolchain\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\system\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\platform\service\udelay\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\protocol\usb\inc" -I"E:\GitHub\Silabs-GG11-USB\USB-composite-Skyworks\gecko_sdk_4.4.3\protocol\usb\src" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"autogen/sl_usbd_init.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


